### ISSUE TITLE
Tool Error Load 1.19.2 - forge 43.2.3 mod version: 1.1.3

### ISSUE THREAD

**Issue by zachsai** [infernalexp/Shield-Expansion#13]
https://gist.github.com/celsiusqc/4f405d830ff4779369ab43513a56692c
Only Iron Tooltip
![image](https://user-images.githubusercontent.com/63996164/211854547-57d76c30-f3b3-4ae0-8e63-c591c77b22f6.png)
![image](https://user-images.githubusercontent.com/63996164/211854570-a1d46940-2b6f-4084-a68c-0f408755450d.png)

**Comment by tinytransfem** [comment]
As far as I can tell the log doesn't actually include anything regarding tooltips. I'll have to try to recreate this on my end, are you playing on a modpack I could download by any chance?

**Comment by tinytransfem** [comment]
Nevermind, the log is just so long that the search function fails lol. Could you maybe provide a log where you do nothing but start the game, check the tooltip, and then close it again? That would be a huge help :)

**Comment by Kuusotare** [comment]
https://gist.github.com/Kuusotare/fc588b9ed398c4d209f30245c7e924bd

This issue also causes the game to crash entirely when attempting to hover over iron shields in Creative.

**Comment by zachsai** [comment]
https://gist.github.com/celsiusqc/37d91981292bfeae8794e398483fea03
here you go, it mentions it in the last block the iron shield

**Comment by zachsai** [comment]
I am using my own modpack, which a new update is in the works for. You could test it with Create Dimensions, Latest Version. You'll just have to update the mod to latest version as that modpack version does not have the new patch yet from your mod

**Comment by tinytransfem** [comment]
Hotfix for this is up on CurseForge, thanks for reporting
