### ISSUE TITLE
Organized Conflict with Shield Expasion

### ISSUE THREAD

**Issue by Klouver-github** [infernalexp/Shield-Expansion#14]
https://paste.gg/p/anonymous/c8b8f21928c247239b78f34208f55668

**Comment by SwanX1** [comment]
could you post the crash report too?

**Comment by SwanX1** [comment]
No need for the crash report!
This is reported at Xaidee/oreganised#11, and it's an issue with Oreganised.

> [Xaidee](https://github.com/Xaidee):
> This is due to changes on the way Shield Expansion registers its shields, a [patch](https://github.com/Xaidee/oreganised/commit/7542f92cb83778bab4a0d6fa6e47610e495a0eaf) for this should be out within the next few days so you can either play without oreganized or revert shield expansion to version 1.0.4 until then

The mod loads without issue with the latest commit (Xaidee/oreganised@18365644aa3d53d667ad8e49fa54fc4869596ffb) of Oreganised.
