### ISSUE TITLE
[Question] About abandoned 1.16.5 Forge

### ISSUE THREAD

**Issue by Kasualix** [infernalexp/Shield-Expansion#17]
I ported this mod to 1.16.5 (version 1.1.5).
If you want to support 1.16.5 (hm, as official), may I send a PR?
If you don't want to support 1.16.5 anymore, may I upload my port on CurseForge as a independent project? 
Sorry I don't know much about mod licenses (or yours, Apache-2.0 license), so I'm not sure whether or not this will be in breach of it.
Or if you just don't want others to get my port version, that's ok, I will not release it. Cuz I'm just a Java leaner for about two months and have kept porting/maintaining mods to get more Java knowledge and don't care a lot about these things.

**Comment by SwanX1** [comment]
Hi there!
**You are free to PR** changes to any branch, as well as fork the project itself.

### Licensing
The Apache License 2.0 requires you to disclose the source code, and keep license and copyright notices. Any new code you write youself in your own project can be licensed under your own license, but that's a hassle, considering you're working in an AL2-licensed codebase.
(Note: this is not legal advice)

We most likely won't pursue any legal action if you release a fork of our project unless it's blatant copying.

**Comment by SwanX1** [comment]
I'll close this issue, since it's not really an issue, and you can communicate more in-depth with us on [our discord](https://infernalstudios.org/discord). Let me know your username and I'll give you the coder role on there.

**Comment by Kasualix** [comment]
My username is Kasualix
![image](https://user-images.githubusercontent.com/110756250/220963319-103ef1c6-da51-4ad2-92d8-f512b0fa9fd3.png)
