### ISSUE TITLE
[Client Start-up CRASH] Mixin config specifies Java version 8 but 1.18 uses version 17

### ISSUE THREAD

**Issue by Cixon** [infernalexp/Shield-Expansion#19]
Hello so this may or may not be a incompatibility with [Atlas Combat](https://www.curseforge.com/minecraft/mc-mods/atlas-combat) but I was told that this issue may need to be investigated by you guys which brings me to this post.

I tested Shield expansion alone on FML 40.2.1 and had no issues on client start up but once I installed [Atlas Combat](https://www.curseforge.com/minecraft/mc-mods/atlas-combat) I was prompted with a crash but no crash report. All the details you need to know regarding this issue will be found below:

**Debug Log (atlas and shield expansion installed):**
[debug.log](https://github.com/infernalstudios/Shield-Expansion/files/10921032/debug.log)

**Comment from Dev and Github:**
https://github.com/Alexandra-Myers/Atlas-Combat/issues/11#issuecomment-1460113639

**Comment by tinytransfem** [comment]
Huh, this is a weird oversight on my part. It's correct in the 1.19 version but I somehow didn't change it in the 1.18 one. Thanks for letting us know, should be fixed very soon!

**Comment by Cixon** [comment]
thank you so much for choosing to fix this issue for a earlier version!

**Comment by Cixon** [comment]
> Huh, this is a weird oversight on my part. It's correct in the 1.19 version but I somehow didn't change it in the 1.18 one. Thanks for letting us know, should be fixed very soon!

### kowalski status report
https://media.tenor.com/wcamYVlI6IAAAAAC/penguins-of-madagascar-skipper.gif

**Comment by tinytransfem** [comment]
Fixed in version 1.1.6

**Comment by Cixon** [comment]
thank you!!
