### ISSUE TITLE
[Suggestion] Custom parry sounds?

### ISSUE THREAD

**Issue by Gemini04126** [infernalexp/Shield-Expansion#31]
I've been snooping around the source code for this mod in an attempt to find a way to make a resource pack that replaces the parry sound with [this](https://www.youtube.com/watch?v=JJzOtii3pRc) without replacing the default experience orb sound. If there's already a way to do this, that'd be fantastic, but I couldn't find one.

**Comment by tinytransfem** [comment]
added in version 1.1.7!
