### ISSUE TITLE
Crash: Rendering screen

### ISSUE THREAD

**Issue by artman41** [infernalexp/Shield-Expansion#47]
| Name                 | Version |
|-------------------|----------|
| Minecraft            | 1.20.1   |
| Minecraft Forge  | 47.3.12 |
| Shield Expansion | 1.1.7a   |

Crash Reports: 

[crash-2024-12-06_23.52.21-client.txt](https://github.com/user-attachments/files/18045204/crash-2024-12-06_23.52.21-client.txt)
[crash-2024-12-06_23.54.22-client.txt](https://github.com/user-attachments/files/18045201/crash-2024-12-06_23.54.22-client.txt)
[crash-2024-12-06_23.55.33-client.txt](https://github.com/user-attachments/files/18045199/crash-2024-12-06_23.55.33-client.txt)

For context, I'm playing on a server and it seems that I crash whenever entering a gui with a damaged shield on my hotbar - unsure whether the shield is broken somehow due to me taking it out of a Refined Storage system.

Offending code seems to be https://github.com/infernalstudios/Shield-Expansion/blob/029922574e272de62289198ff7752af4bf353adc/src/main/java/org/infernalstudios/shieldexp/events/ShieldExpansionEvents.java#L244-L247

So I'm assuming either `SHIELD_STATS.get(key)` or `SHIELD_STATS.get("shieldexp:default")` is returning null(?)

**Comment by SwanX1** [comment]
Fixed by #49
