### ISSUE TITLE
[SE 1.0.2 - 1.18.2] Walking diagonally while holding a shield is faster than forwards, backwards and sideways.

### ISSUE THREAD

**Issue by Thombias** [infernalexp/Shield-Expansion#5]
Title pretty much describes the whole bug or oversight i'm currently experiencing with the mod.
I'll put a video link here in case it's unclear what i mean: https://streamable.com/cqynuc

**Comment by tinytransfem** [comment]
This is not a bug, it's how vanilla Minecraft handles walking speed - if you walk diagonally while sneaking or blocking in vanilla Minecraft you also walk faster than if you only walk in one direction. There is no way to "fix" that as that's simply how the game works.

**Comment by Thombias** [comment]
Ah i see why i never noticed this on vanilla. The movement speed is so slow on the vanilla shield while blocking to the point it isn't even noticable unless you really pay attention to it. Sorry, my bad! Since the shields from your mod have higher movement speed it immediately caught my attention. x')
