### ISSUE TITLE
Shield speed boost bug

### ISSUE THREAD

**Issue by ChakaClown** [infernalexp/Shield-Expansion#6]
The version of forge I'm on is 1.18.2. (May be on other versions of the game)

When you hold down your attack button and right click and un-right click with a wooden shield you can go super fast. (This may bug may work with other shields as well)

**Comment by tinytransfem** [comment]
This is known and has to do with how the game handles item cooldowns – I'm currently working on a fix.

**Comment by LordCodFish** [comment]
> This is known and has to do with how the game handles item cooldowns – I'm currently working on a fix.

It's happening to me too, on 1.19.2

**Comment by IlTAKlI** [comment]
It's easy to replicate with the better combat mod installed too, it's as simple as swinging your sword right as you stop blocking

**Comment by tinytransfem** [comment]
fixed in 1.0.3
