### ISSUE TITLE
Big Brain Buckler Cooldown

### ISSUE THREAD

**Issue by DeltaGlitch** [infernalexp/Shield-Expansion#7]
I was using this mod and Big Brain in a pack I made, and when I used the Buckler, I noticed that the cooldown was changed drastically. It refreshed wayyy quicker than it should have, leading it to be really busted for movement. I guess that the Buckler was considered a shield by this mod, so it replaced the already existing cooldown with this mod's shorter one. I hope this gets fixed soon! Thanks.

**Comment by tinytransfem** [comment]
Better late than never: this is fixed in today's 1.1.0 update
